add_newline = false
command_timeout = 1000

[character]
success_symbol = "🦄 " 
error_symbol = "🥺 "

[git_status]
# disabled = true
style = "bold white"
conflicted = " 🏳"
ahead = " 🏎💨 "
behind =" 😰 "
diverged = " 😵 "
untracked = " 🤷‍ "
stashed = " 📦 "
modified = " 📝 "
staged = '[++\($count\)](green)'
renamed = " 👅 "
deleted = " 🗑 "

[gcloud]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true
