general.live_config_reload = true

[colors]
# Primary colors (Gruvbox Dark)
primary = { background = '#282828', foreground = '#ebdbb2' }

# Normal colors
normal = { black = '#1d2021', red = '#fb4934', green = '#8ec07c', yellow = '#faf27a', blue = '#83a598', magenta = '#d3869b', cyan = '#8ec07c', white = '#ebdbb2' }

# Bright colors
bright = { black = '#928374', red = '#fb4934', green = '#8ec07c', yellow = '#faf27a', blue = '#83a598', magenta = '#d3869b', cyan = '#8ec07c', white = '#ebdbb2' }

# Cursor colors
cursor = { text = '#282828', cursor = '#ebdbb2' }

# Selection colors
selection = { text = '#ebdbb2', background = '#3c3836' }

#[colors.bright]
#black = "0x997e9d"
#blue = "0x7da6ff"
#cyan = "0x0db9d7"
#green = "0xb9f27c"
#magenta = "0xbb9af7"
#red = "0xff7a93"
#white = "0xacb0d0"
#yellow = "0xff9e64"
#
#[colors.normal]
#black = "0x32344a"
##blue = "0x7aa2f7"
#cyan = "0x449dab"
#green = "0x9ece6a"
#magenta = "0xad8ee6"
#red = "0xf7768e"
#white = "0x787c99"
#yellow = "0xe0af68"
#
#[colors.primary]
#background = "0x1a1b26"
#foreground = "0xa9b1d6"

[font]
size = 12

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
y = 5

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Period"
mode = "~Search"
mods = "Control"

[[keyboard.bindings]]
action = "None"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "W"
mods = "Command"

[terminal.shell]
args = ["new-session", "-D", "-c", "#{pane_current_path}"]
# program = "/usr/local/bin/tmux"
program = "/opt/homebrew/bin/tmux"

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.95

[window.padding]
x = 2
y = 2
